# Welcome to Jekyll!
title: Eye tracking
email: guilhembarboux@gmail.com
description: Exploring eye tracking
baseurl: "/"
url: ""

# Files settings
include:
  - opencv/1/cv.data

# Build settings
livereload: true
source: ./site
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-livereload
